version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:*"
        update-types:
          - "minor"
          - "patch"

      testing:
        patterns:
          - "org.wiremock.integrations:*"
        update-types:
          - "minor"
          - "patch"

      build-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
          - "org.jacoco:*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
