osrm.zone-manager.data-dir=${user.dir}/local-data
osrm.zone-manager.base-pbf=${user.dir}/local-data/base/italy.osm.pbf
osrm.zone-manager.reduce-script=${user.dir}/src/main/scripts/reduce.py
spring.datasource.url=jdbc:postgresql://localhost:5432/osrm_zone_manager
spring.datasource.username=osrm
spring.datasource.password=osrm
logging.level.it.bluecube.osrmzonemanager=debug
